// This file has been generated by Tauri Specta. Do not edit this file manually.
//
// NOTE: regenerate with `npm run bindings:export`, then reconcile the output
// against the frontend source-of-truth types in `src/types/index.ts`. The raw
// export uses tabs, double quotes and snake_case fields, and marks optionals
// `| null`; run it through prettier and adjust the shapes by hand. The parity
// test in `bindings-parity.test.ts` verifies the command list survived that
// reconciliation, which is the part that silently rots.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from '@tauri-apps/api/event';

/** Commands */
export const commands = {
  fetchGameManifest: (url: string) =>
    typedError<GameManifest, LauncherError>(__TAURI_INVOKE('fetch_game_manifest', { url })),

  fetchRemoteText: (url: string) =>
    typedError<string, LauncherError>(__TAURI_INVOKE('fetch_remote_text', { url })),

  installGame: (manifest: GameManifest, baseUrl: string, onEvent: Channel<DownloadEvent>) =>
    typedError<GameInstallation, LauncherError>(
      __TAURI_INVOKE('install_game', { manifest, baseUrl, onEvent })
    ),

  checkGameUpdate: (gameId: string, manifest: GameManifest) =>
    typedError<boolean, LauncherError>(__TAURI_INVOKE('check_game_update', { gameId, manifest })),

  verifyGame: (manifest: GameManifest, installPath: string, onEvent: Channel<VerifyProgress>) =>
    typedError<VerificationResult, LauncherError>(
      __TAURI_INVOKE('verify_game', { manifest, installPath, onEvent })
    ),

  launchGame: (gameId: string, gameName?: string | null) =>
    typedError<LaunchResult, LauncherError>(
      __TAURI_INVOKE('launch_game', { gameId, gameName: gameName ?? null })
    ),

  closeGame: (gameId: string) =>
    typedError<void, LauncherError>(__TAURI_INVOKE('close_game', { gameId })),

  getInstalledGames: () =>
    typedError<GameInstallation[], LauncherError>(__TAURI_INVOKE('get_installed_games')),

  getGameInstallation: (gameId: string) =>
    typedError<GameInstallation | null, LauncherError>(
      __TAURI_INVOKE('get_game_installation', { gameId })
    ),

  uninstallGame: (gameId: string) =>
    typedError<void, LauncherError>(__TAURI_INVOKE('uninstall_game', { gameId })),

  getSettings: () => typedError<LauncherSettings, LauncherError>(__TAURI_INVOKE('get_settings')),

  saveSettings: (newSettings: LauncherSettings) =>
    typedError<void, LauncherError>(__TAURI_INVOKE('save_settings', { newSettings })),

  markTrayHintShown: () => typedError<void, LauncherError>(__TAURI_INVOKE('mark_tray_hint_shown')),

  selectInstallFolder: (start?: string | null) =>
    typedError<string | null, LauncherError>(
      __TAURI_INVOKE('select_install_folder', { start: start ?? null })
    ),

  getDefaultInstallFolder: () =>
    typedError<string, LauncherError>(__TAURI_INVOKE('get_default_install_folder')),

  cancelOperation: () => typedError<void, LauncherError>(__TAURI_INVOKE('cancel_operation')),

  getAppDataDir: () => typedError<string, LauncherError>(__TAURI_INVOKE('get_app_data_dir')),

  setLauncherUpdateAvailable: (available: boolean) =>
    typedError<void, LauncherError>(__TAURI_INVOKE('set_launcher_update_available', { available })),

  quitLauncher: () => typedError<void, LauncherError>(__TAURI_INVOKE('quit_launcher')),
};

/** Events */
export const events = {
  gameExited: makeEvent<GameExited>('game-exited'),
};

/* Types */

export type DownloadEvent =
  | {
      event: 'Started';
      data: {
        filePath: string;
        totalSize: number;
        fileIndex: number;
        totalFiles: number;
        /** Whole-build byte totals, so the bar moves even for files too small to
         * emit a progress update of their own. */
        overallDownloaded?: number;
        overallTotal?: number;
      };
    }
  | {
      event: 'Progress';
      data: {
        filePath: string;
        downloaded: number;
        total: number;
        speedBps: number;
        overallDownloaded?: number;
        overallTotal?: number;
        completedFiles?: number;
        totalFiles?: number;
        currentFile?: string;
      };
    }
  | {
      event: 'FileComplete';
      data: {
        filePath: string;
        completedFiles?: number;
        totalFiles?: number;
        overallDownloaded?: number;
        overallTotal?: number;
      };
    }
  | {
      event: 'Retry';
      data: { filePath: string; attempt: number; maxAttempts: number; error: string };
    }
  | { event: 'Complete'; data: { completedFiles: number; totalFiles: number } }
  | { event: 'Error'; data: { message: string } };

export type FileEntry = {
  path: string;
  hash: string;
  size: number;
  url: string;
  compress?: boolean;
};

export type GameExited = {
  game_id: string;
  duration_seconds: number;
};

export type GameInstallation = {
  game_id: string;
  installed_version: string;
  installed_build: number;
  channel: string;
  install_path: string;
  installed_files: Record<string, string>;
  installed_at: string;
  last_played: string | null;
  total_playtime_seconds: number;
  executable: string;
};

export type GameManifest = {
  game_id: string;
  name: string;
  version: string;
  build_number: number;
  channel: string;
  description?: string;
  icon_url?: string;
  banner_url?: string;
  executable: string;
  files: FileEntry[];
};

export type LauncherError =
  | { code: 'NotInstalled' }
  | { code: 'AlreadyRunning' }
  | { code: 'NotRunning' }
  | { code: 'ExecutableNotFound'; details: { path: string } }
  | { code: 'PathNotAllowed'; details: { path: string } }
  | { code: 'Network'; details: string }
  | { code: 'ManifestParse'; details: string }
  | { code: 'Validation'; details: string }
  | { code: 'Io'; details: string }
  | { code: 'Other'; details: string };

export type LauncherSettings = {
  gamesInstallPath: string | null;
  maxDownloadSpeed: number | null;
  maxConcurrentDownloads: number;
  autoUpdateGames: boolean;
  autoUpdateLauncher: boolean;
  closeToTray: boolean;
  trayHintShown: boolean;
  language: string;
  theme: string;
  notifyGameUpdates: boolean;
  notifyDownloadComplete: boolean;
};

export type LaunchResult = {
  success: boolean;
  message: string;
  processId: number | null;
};

export type VerificationResult = {
  valid_files: number;
  invalid_files: string[];
  missing_files: string[];
  is_valid: boolean;
};

/** How one file fared. Mirrors FileCheck in src-tauri/src/types.rs. */
export type FileCheck = 'valid' | 'invalid' | 'missing';

export type VerifyProgress = {
  path: string;
  state: FileCheck;
  checked: number;
  total: number;
  valid: number;
  invalid: number;
  missing: number;
};

/* Tauri Specta runtime */

async function typedError<T, E>(
  result: Promise<T>
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: 'error', error: e as E };
  }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(
  name: string,
  serialize?: (payload: T) => unknown,
  deserialize?: (payload: unknown) => T
) {
  const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<unknown>) =>
    cb({
      ...event,
      payload: deserialize ? deserialize(event.payload) : (event.payload as T),
    });
  const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  };

  const fn = (
    target: import('@tauri-apps/api/webview').Webview | import('@tauri-apps/api/window').Window
  ) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
    emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  });

  return Object.assign(fn, base);
}
